# Generated by Django 3.1.7 on 2021-07-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=15)),
                ('adresse', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Moniteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolDrive.personne')),
                ('date_rcrutement', models.DateField()),
            ],
            bases=('schoolDrive.personne',),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('horaire', models.DateTimeField(auto_now=True)),
                ('type_formation', models.CharField(max_length=50)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolDrive.personne')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolDrive.vehicule')),
            ],
        ),
    ]
