# Generated by Django 3.1.7 on 2021-07-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='telephone',
            field=models.IntegerField(default=24555),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personne',
            name='adresse',
            field=models.CharField(max_length=30),
        ),
    ]
